WIP: See description.
- Fixed README.md errors/issues.
- Created a workaround for util-linux
- Broke apart some of the commands for better debugging.
- Changed the Dockerfiles for readability.
- In the future, i'll submit pull requests that'll break down the tags to also do PHP 7.0 to 7.4 to latest

still getting the below on the README build:
```bash
Creating ci_sut_1 ... error

ERROR: for ci_sut_1  Cannot start service sut: Cannot link to a non running container: /ci_web1604-php7_1 AS /ci_sut_1/ci_web1604-php7_1

ERROR: for sut  Cannot start service sut: Cannot link to a non running container: /ci_web1604-php7_1 AS /ci_sut_1/ci_web1604-php7_1
ERROR: Encountered errors while bringing up the project.
```